<?php 
$captcha=$viewParams['captcha'];
$token =$viewParams['token'];
?>
<form class="form-signin" method="post">
	<h2 class="form-signin-heading">Please sign in</h2>
	<input type="text" name="email" class="form-control" placeholder="Email address" required autofocus>
	<input type="password" name="password" class="form-control" placeholder="Password" required>
	<?php echo $captcha;?>
	<input type="hidden" name="csrf" value="<?=$token;?>"/>
	<label class="checkbox">
		<input type="checkbox" value="remember-me"> Remember me
	</label>
	<button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
</form>